### ISSUE TITLE
Flexible measurements

### ISSUE THREAD

**Issue by giangiac** [sandialabs/pyGSTi#282]
I am not sure if what I am asking is already possible, but I could not find the documentation to implement it.

**Situation:**
I would like to create a model with local noise such that the measurement layer is not 'Mdefault' but can be customized using two types of measurements:  
1) single qubit measurement in the Z basis
2) two-qubit parity measurement (returning 0 for the even subspace and 1 for the odd subspace)

Furthermore, I would like to explicitly indicate which qubit are measured with single-qubit measurements, which pairs of qubit undergo a parity measurement, and which qubits are left unmeasured.

If this is already possible, could you provide an example?  
Otherwise is there interest in such extension?

**Comment by aristaeus** [comment]
I don't know if there's a better way to do this, but the workaround I have found is to extract the density matrix and do the measurement myself.

- Simulate using method 2 here: https://github.com/pyGSTio/pyGSTi/blob/4e0cdc2b47014ea718629bc21c2122d3a83ff028/jupyter_notebooks/Tutorials/algorithms/CircuitSimulation.ipynb
- Convert the simulation state rho to a numpy array
- Apply the projector manually
- Convert back to a pyGSTi state for continuing simulation

I found the functions to go to and from a numpy array in this notebook: https://github.com/pyGSTio/pyGSTi/blob/master/jupyter_notebooks/Tutorials/objects/advanced/Operators.ipynb

Rough code example, needs a bit of polishing to be generally useful
```python
rho = mdl.operation_blks['layers'][('Gh', 0)].acton(rho)
print(rho)
pygsti.tools.ppvec_to_stdmx(rho)
dm = p_z0 * pygsti.tools.ppvec_to_stdmx(rho) # multiply by our projector
dm = dm / np.trace(dm) # renormalise
rho = pygsti.modelmembers.states.StaticState(pygsti.tools.stdmx_to_ppvec(dm))
```

**Comment by sserita** [comment]
Apologies on the super delayed response to this. In fact, this sort of thing is of interest and we have incorporated it into pyGSTi. There is now a tutorial notebook on custom POVMs, including mixing computational basis and parity measurements as of pyGSTi 0.9.12.1: https://github.com/sandialabs/pyGSTi/blob/master/jupyter_notebooks/Tutorials/objects/advanced/CustomPOVM.ipynb
