### ISSUE TITLE
Add Interleaved RB 

### ISSUE THREAD

**Issue by Shuoming** [sandialabs/pyGSTi#296]
**Is your feature request related to a problem? Please describe.**
I tried this package for a while. It helps a lot. But among all its RBs,  a very commonly used type of interleaved RB is not included in this package. https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.109.080505.

**Describe the solution you'd like**
I hope the interleaved RB protocol is added as other RB protocols.

**Comment by coreyostrove** [comment]
Hi @Shuoming, thanks for the suggestion. We'll certainly take this into consideration when considering the next round of feature updates for pygsti. Unfortunately, adding support for interleaved RB is not very high on our current list of priorities, so I couldn't say when or if we'd able to get around to this on our end.

That said, pygsti is an open source project and there no reason you or anyone else needs to wait for us on the core dev team to get around to it if this is a feature that a lot of folks want. That is to say, if someone in the greater pygsti community was interested in building out this capability and submitting a pull request that would be awesome and we'd happily work with them to integrate those changes into the main codebase.

**Comment by sserita** [comment]
Completed with #468
