### ISSUE TITLE
Add warnings to notebook reports about jupyter-lab compatibility

### ISSUE THREAD

**Issue by coreyostrove** [sandialabs/pyGSTi#328]
This is not a new problem, but the notebook option for GST reports is, and likely will continue to be, incompatible with jupyterlab. This isn't well documented in pygsti, however, which is easy to fix. We should do the following:

1. Have the write_notebook method for reports produce a warning alerting users to the compatibility problem. Similarly add a note to the docstring.
2. Add a note to the reporting tutorial.
3. Add a note at the top of the produced .ipynb file itself.

**Comment by sserita** [comment]
Fixed on branch `bugfix-example-updates` via commit `a0e4d5d`. This branch will stay open for now while we get fixes for #317 in as well.
