### ISSUE TITLE
Unexpected file in test_packages

### ISSUE THREAD

**Issue by coreyostrove** [sandialabs/pyGSTi#381]
This is primarily a question for @enielse. I'm working through some changes in `test_packages` and noticed an unexpected file in `test_packages\drivers` called `nqubitconstruction.py`. This isn't a test module, but rather looks to me like it might be an early/outdated version of the cloud noise model code. I suspect this is probably from when you were originally testing that code and it probably slipped into a commit by accident, and therefore can be safely deleted. But I wanted to run that by you first before I did so. It might also be worth having you take a look to make sure there aren't any functions or code within that ought to be preserved before we remove it entirely. Thoughts?

**Comment by enielse** [comment]
This looks fine to remove to me.  The code in `nqubitconstruction.py` has been incorporated into pygsti proper.  I believe earlier on this file *was* used by the unit tests but since adding functionality to the cloud crosstalk models this is no longer needed.

**Comment by sserita** [comment]
Thanks @enielse! I've removed this file in my `bugfix-release-0.9.12.1` branch which I plan to use as a catchall for several of the smaller bugfixes for the next release.
