### ISSUE TITLE
Pygsti is incompatible with scipy 1.12

### ISSUE THREAD

**Issue by eendebakpt** [sandialabs/pyGSTi#391]
**Describe the bug**
 Using pygsti fails on the import of colvolve from scipy (which is no longer available from the main scipy namespace in version 1.12)

**To Reproduce**
1. Install scipy 1.12 (latest on pypi) and pygsti
2. Using pygsti fails on the import of colvolve from scipy at line

https://github.com/sandialabs/pyGSTi/blob/7411a00ec81e67f50932b705e46426fc2d4701d8/pygsti/extras/drift/signal.py#L13

**Environment (please complete the following information):**
 - pyGSTi version [e.g. v0.9.7.4] '0.9.10.1.post449'
 - python version [e.g. 3.7, 2.7] 3.11
 - OS [e.g. OSX 10.14, Ubuntu 16.04 LTS] Windows

**Comment by sserita** [comment]
Fixed in #392
