### ISSUE TITLE
How to characterize crosstalk errors with PyGsti?

### ISSUE THREAD

**Issue by Lucas-Reed** [sandialabs/pyGSTi#404]
In the paper "Experimental Characterization of Crosstalk Errors with Simultaneous Gate Set Tomography", the authors used PyGsti to fit the crosstalk model to the experimental data. Is this operation built into PyGsti? Is it possible to accomplish this with a few lines of code?

**Comment by sserita** [comment]
Closing this as part of issue cleanup for the next minor release as we answered the question. Please reach out again if this example was not a sufficient starting point!
