### ISSUE TITLE
RB edesigns' `truncate_to_available_data` fails to truncate auxiliary information

### ISSUE THREAD

**Issue by jordanh6** [sandialabs/pyGSTi#408]
MirrorRBDesign.truncate_to_available_data truncates the the edesign's circuit_lists, but it does not truncate idealout_lists. This means that the mapping between circuits and target bit strings is lost. 

Example notebook attached. 

Expected behavior: Returned edesign should have idealout_lists that contain exactly the idealouts of the circuits remaining in the truncated design. 

Based on skimming the code I suspect other RB protocol edesigns have an analogous issue. 

Environment:
 - pyGSTi v0.9.12.1
 - python 3.8

[edesign-truncate-bug.zip](https://github.com/sandialabs/pyGSTi/files/14519065/edesign-truncate-bug.zip)

**Comment by sserita** [comment]
Closing as this is merged in develop with #443
