### ISSUE TITLE
HTML Reports for Non-Gauge Optimized Models 

### ISSUE THREAD

**Issue by pcwysoc** [sandialabs/pyGSTi#412]
**Describe the bug**
When gauge optimization is not performed during GST the HTML report does not generate the gauge-dependent figures. There is a similar, less critical, problem for notebook reports. 

**To Reproduce**

[GaugeOptReportBug.ipynb.zip](https://github.com/sandialabs/pyGSTi/files/14749681/GaugeOptReportBug.ipynb.zip)

**Expected behavior**
I believe that the raw estimates and error metrics should still generate, although they won't be as informative. Otherwise, there should be some flag to remove the gauge-dependent sections of the report. 

**Environment (please complete the following information):**
 - pyGSTi version qiskit-feature-mcm
 - python version 3.10
 - OS 13.6.5

**Comment by coreyostrove** [comment]
Thanks for the bug report, @pcwysoc! And for the example code reproducing the error. I have implemented a fix for this (along with some other issues I discovered along the way) on the branch 'feature-circuitlistsdesign-reporting'. These should be merged into develop sometime soon (there is already a PR for these changes), but in the meantime you can merge that branch into your own if you need this working right away.

**Comment by sserita** [comment]
Closing as this is now merged in with #415
