### ISSUE TITLE
legacyio.py contains no executable code.

### ISSUE THREAD

**Issue by rileyjmurray** [sandialabs/pyGSTi#424]
All of the code in this file has been commented out. I suggest we delete the file.

https://github.com/sandialabs/pyGSTi/blob/ee2158575f4a6a9cffa7465983054be13772e0f8/pygsti/io/legacyio.py#L1-L385

**Comment by sserita** [comment]
Agreed. I think the next release we are anticipating is 0.9.13, which will have other deletions/deprecations (i.e. Qibo). So we can go ahead and delete this as part of that.

**Comment by rileyjmurray** [comment]
Note: At time of commenting, PR #451 includes an incidental change that would resolve this issue. However, I just opened PR #452 that's dedicated to the broader problem of removing commented-out code.

**Comment by sserita** [comment]
Closed with #451
