### ISSUE TITLE
Numpy version dependency

### ISSUE THREAD

**Issue by manavbabel** [sandialabs/pyGSTi#470]
**Describe the bug**
When importing `pygsti` in an environment with `numpy==2.0.0`, an error is thrown saying the module `numpy.lib.arraysetops` is not found. I think this was removed in that version of numpy. The bug is fixed when numpy version `1.26.0` is used, so I suggest modifying the requirements file to specify this.

**To Reproduce**
In terminal:
`pip install numpy pygsti` # installs version 2.0.0 or above
In the Python environment:
`import pygsti`
Result:
`ModuleNotFoundError: No module named 'numpy.lib.arraysetops'`
Fixed with:
`pip install numpy==1.26.0`

**Environment (please complete the following information):**
 - pyGSTi version 0.9.12.3
 - numpy version 2.0.0
 - python version 3.11
 - OS Windows 10

**Comment by coreyostrove** [comment]
Thanks for your report. This will be fixed with PR #458, and the fix should be available on the develop branch within the next few days. If you run into any other numpy 2.0 related issues please don't hesitate to let us know.

**Comment by sserita** [comment]
Fixed in #458
