### ISSUE TITLE
Serialization for ModelEstimateResults

### ISSUE THREAD

**Issue by eendebakpt** [sandialabs/pyGSTi#475]
**Is your feature request related to a problem? Please describe.**

When using `pygsti.serialization.json.dump` to serialize an object of type `ModelEstimateResults` a warning is generated. 
```
The function dump is deprecated, and may not be present in future versions of pygsti.
    Please use Use of the python json module for serialization of pygsti objects is deprecated. Most pysgti objects now natively support json serialization and deserialization and users should migrate to that functionality when possible. instead.
```
But the `ModelEstimateResults`is not serializable by plain json:
```

  File C:\Python310\lib\json\encoder.py:179 in default
    raise TypeError(f'Object of type {o.__class__.__name__} '

TypeError: Object of type ModelEstimateResults is not JSON serializable
```

**Describe the solution you'd like**

Serialize the `ModelEstimateResults` without warning. Preferable with plain json.

**Describe alternatives you've considered**

None yet

**Additional context**
 
-

**Comment by sserita** [comment]
As stated in the warning, JSON serialization is deprecated and we are unlikely to implement this feature as requested. `ModelEstimateResults` objects should be able to be serialized by using the `.write()` member function, and loaded using either `pygsti.io.load_results_from_dir()` or `ModelEstimateResults.from_dir()`. It is not just a JSON format; instead, it uses the pyGSTi metadir approach (which does serialize as many objects to JSON as possible, but not always).

Please try the `write()` and `from_dir()` and see if that is a workable solution for you.

**Comment by eendebakpt** [comment]
Ah I see. I thought the pygsti json method could be replaced with the json module. The `write` and `from_dir` are not as convenient, but we can work with them.

@sserita Thanks for clarification, I'll close the issue
