### ISSUE TITLE
FOGI Labels Exponential Blowup

### ISSUE THREAD

**Issue by juangmendoza19** [sandialabs/pyGSTi#486]
When running GST with a FOGI model, the output model's labels get messed up. It seems like every iteration, the model gets rebuilt and during the label construction it includes a combination of the previous labels. Creating a nested pattern of labels which grows at an exponential rate, and causing huge memory consumption. Pointed out by @jordanh6 

#Create a FOGI model
import pygsti
from pygsti.modelpacks import smq1Q_XY as std
import numpy as np
from FOGI.fogi import create_fogiASMP_smq1Q_XY_model
fogi_model = create_fogiASMP_smq1Q_XY_model(pygsti_model=True)

#Generate data to run GST
datagen_model = std.target_model("GLND")
errgen_vector = np.zeros(datagen_model.num_params)
errgen_vector[4] = .1
datagen_model.from_vector(errgen_vector)
design = std.create_gst_experiment_design(32)
dataset = pygsti.data.simulate_data(datagen_model, 
design.all_circuits_needing_data,
    num_samples=100000, seed=20230217, sample_error='none')

data = pygsti.protocols.ProtocolData(design, dataset)

#Run GST
protoOpt = pygsti.protocols.GateSetTomography(fogi_model, verbosity=0, gaugeopt_suite=None)

**Expected behavior**
The labels of the result model should be unchanged

**Environment:**
 - pyGSTi version 0.9.12.3
 - python version 3.10.14
 - macOS 14.6.1

**Comment by sserita** [comment]
Completed with #488
